# Generated by Django 2.0.1 on 2018-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20180323_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
