# Generated by Django 2.0.1 on 2018-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_idea_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideavote',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
