# Generated by Django 2.0.1 on 2018-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_idea_newest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
