# Generated by Django 2.0.1 on 2018-04-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_version_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='submitter',
        ),
    ]
