# Generated by Django 2.0.1 on 2018-03-22 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, unique=True)),
                ('change', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('features_game', models.CharField(default='', max_length=200)),
                ('features_design', models.CharField(default='', max_length=200)),
                ('features_selection', models.CharField(default='', max_length=200)),
                ('features_website', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
