# Generated by Django 2.0.1 on 2018-04-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='submitter',
            field=models.CharField(default='', max_length=200),
        ),
    ]
