# Generated by Django 2.0.1 on 2018-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180413_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='idea_nr',
            field=models.IntegerField(default=-1),
        ),
    ]
