# Generated by Django 2.0.1 on 2018-06-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0003_auto_20180601_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='postSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site0', models.TextField(default='', null=True)),
                ('site1', models.TextField(default='', null=True)),
                ('site2', models.TextField(default='', null=True)),
                ('site3', models.TextField(default='', null=True)),
                ('site4', models.TextField(default='', null=True)),
                ('site5', models.TextField(default='', null=True)),
                ('site6', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnairePost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnairePre', to=settings.AUTH_USER_MODEL),
        ),
    ]
