# Generated by Django 2.0.1 on 2018-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, null=True)),
                ('site0', models.TextField(default='')),
                ('site1', models.TextField(default='')),
                ('site2', models.TextField(default='')),
                ('site3', models.TextField(default='')),
                ('site4', models.TextField(default='')),
            ],
        ),
    ]
