# Generated by Django 2.0.1 on 2018-06-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20180621_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey0',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ABSurvey9',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='Age_Combobox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='DesignProcess_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='EverDesignedApp_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='EverDesignedVG_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='Gender_Combobox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='HeardPBN_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='HoursPCWeek_Combobox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='HowInDesignProcess_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='IdeaPBN_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ImportantAspect_Checkbox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='LikePBN_7scale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='LikePlatformersMore_7scale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='LikePlatformers_7scale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='LikeTP_7scale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='MostImportantAspect_Radiolist',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='ParticipateTP_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='PlayPBN_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='PlayPlatformers_7scale',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='VideogamesWeek_Combobox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='WatchedTP_bool',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
