# Generated by Django 2.0.1 on 2018-06-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180621_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsurvey',
            name='site1',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='site2',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='site3',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='site4',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='site5',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='site6',
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ09',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ13',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ14',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ15',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ16',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ17',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ18',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ19',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ20',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ21',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ22',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ23',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ24',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ25',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ26',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ27',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ28',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ29',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ30',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ31',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GEQ32',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General09',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM09',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='KIM11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ09',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ13',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ14',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ15',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ16',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ17',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ18',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ19',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SPGQ20',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='SUS09',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
