# Generated by Django 2.0.1 on 2018-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20180622_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='presurvey',
            name='ImportantAspectOther_Checkbox',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='MostImportantAspectOther_Radiolist',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
