# Generated by Django 2.0.1 on 2018-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20180626_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsurvey',
            name='GAM00',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM01',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM02',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM03',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM04',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM05',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM06',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM07',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM08',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM09',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM13',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM14',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM15',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM16',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM17',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM18',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM19',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM20',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM21',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM22',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM23',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM24',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM25',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='GAM26',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General13',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General14',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='General15',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
