# Generated by Django 2.0.1 on 2018-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20180927_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsurvey',
            name='General16',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
