# Generated by Django 2.0.1 on 2019-10-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_postsurvey_general16'),
    ]

    operations = [
        migrations.AddField(
            model_name='presurvey',
            name='Job',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
