# Generated by Django 2.0.1 on 2019-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20191106_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='site0',
            field=models.TextField(default='', null=True),
        ),
    ]
