# Generated by Django 2.0.1 on 2019-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_registrationform_site0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='site0',
            new_name='csrf',
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
