# Generated by Django 2.0.1 on 2018-03-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='manageable',
            new_name='feasible',
        ),
    ]
