# Generated by Django 2.0.1 on 2018-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20180311_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.CharField(default='0,01', max_length=25),
        ),
    ]
