# Generated by Django 2.0.1 on 2018-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20180425_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ideavote',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
