# Generated by Django 2.0.1 on 2018-03-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20180312_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='implemented',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='manageable',
        ),
        migrations.AddField(
            model_name='idea',
            name='implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='manageable',
            field=models.BooleanField(default=True),
        ),
    ]
