# Generated by Django 2.0.1 on 2018-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_auto_20180601_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='implemented_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='time_needed',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
