# Generated by Django 2.0.1 on 2018-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_auto_20180626_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='rater1',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='rater2',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='raterfinal',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
