# Generated by Django 2.0.1 on 2018-07-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_auto_20180627_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to='website.Version'),
        ),
    ]
