# Generated by Django 2.0.1 on 2018-07-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20180706_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to='website.Version'),
        ),
    ]
