# Generated by Django 2.0.1 on 2018-08-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_auto_20180802_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='currently_implemented',
            field=models.BooleanField(default=False),
        ),
    ]
