# Generated by Django 2.0.1 on 2018-09-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_auto_20180803_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date_chosen',
            field=models.DateTimeField(null=True),
        ),
    ]
