# Generated by Django 2.0.1 on 2018-10-05 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_version_idea_nr'),
        ('ideas', '0024_auto_20180930_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('admin_comment', models.CharField(default='', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugreport', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(default=42, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bugreport', to='website.Version')),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to='website.Version'),
        ),
    ]
