# Generated by Django 2.0.1 on 2019-10-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0025_auto_20181005_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugr3eport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bugreport', to='website.Version'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to='website.Version'),
        ),
    ]
