# Generated by Django 2.0.1 on 2018-01-31 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_started', models.IntegerField(default=0)),
                ('rounds_won', models.IntegerField(default=0)),
                ('rounds_lost', models.IntegerField(default=0)),
                ('enemies_killed', models.IntegerField(default=0)),
                ('coins_collected', models.IntegerField(default=0)),
                ('highscore', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo', to='website.Version')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_game', models.IntegerField(default=0)),
                ('time_spent_ideas', models.IntegerField(default=0)),
                ('time_spent_index', models.IntegerField(default=0)),
                ('time_spent_history', models.IntegerField(default=0)),
                ('time_spent_chat', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websiteinfo', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websiteinfo', to='website.Version')),
            ],
        ),
    ]
