# Generated by Django 2.0.1 on 2018-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_gameinfo_websiteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='rounds_lost',
        ),
    ]
