# Generated by Django 2.0.1 on 2018-03-22 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_websiteinfo_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_per_page', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtersettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
