# Generated by Django 2.0.1 on 2018-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_gameinfo_rounds_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
