# Generated by Django 2.0.1 on 2018-04-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180413_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo', to='website.Version'),
        ),
    ]
