# Generated by Django 2.0.1 on 2018-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_gameinfo_deaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vote_weight',
            field=models.IntegerField(default=3),
        ),
    ]
