# Generated by Django 2.0.1 on 2018-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='highest_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='movement_inputs',
            field=models.IntegerField(default=0),
        ),
    ]
