# Generated by Django 2.0.1 on 2018-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20180706_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='versionlabel',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
