# Generated by Django 2.0.1 on 2018-07-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20180708_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vote_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='version',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo', to='website.Version'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='version',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='websiteinfo', to='website.Version'),
        ),
    ]
