# Generated by Django 2.0.1 on 2018-09-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20180802_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='eastereggs_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='special_name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='version',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo', to='website.Version'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='version',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='websiteinfo', to='website.Version'),
        ),
    ]
