# Generated by Django 2.0.1 on 2018-09-18 14:03

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20180918_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uploaded_character',
            field=models.ImageField(null=True, upload_to=authentication.models.character_upload, validators=[authentication.models.validate_character_size]),
        ),
    ]
