# Generated by Django 2.0.1 on 2018-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20180918_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='character',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
