# Generated by Django 2.0.1 on 2018-09-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20180919_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='version',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo', to='website.Version'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='version',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.DO_NOTHING, related_name='websiteinfo', to='website.Version'),
        ),
    ]
