# Generated by Django 2.0.1 on 2018-09-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20180930_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
