# Generated by Django 2.0.1 on 2018-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20181005_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
