# Generated by Django 2.0.1 on 2018-04-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameinfo', to='website.Version'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='websiteinfo', to='website.Version'),
        ),
    ]
