# Generated by Django 2.0.1 on 2018-04-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180413_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
    ]
