# Generated by Django 2.0.1 on 2018-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180418_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vote_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
