# Generated by Django 2.0.1 on 2018-03-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('website', '0001_initial'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('requests_left', models.IntegerField(default=1)),
                ('votes_left', models.IntegerField(default=1)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=True)),
                ('survey_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_started', models.IntegerField(default=0)),
                ('rounds_won', models.IntegerField(default=0)),
                ('enemies_killed', models.IntegerField(default=0)),
                ('coins_collected', models.IntegerField(default=0)),
                ('highscore', models.IntegerField(default=-1)),
                ('time_spent_game', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameinfo', to='website.Version')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_ideas', models.IntegerField(default=0)),
                ('time_spent_index', models.IntegerField(default=0)),
                ('time_spent_history', models.IntegerField(default=0)),
                ('time_spent_chat', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websiteinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
