# Generated by Django 2.0.1 on 2018-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_gameinfo_jumps'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vote_weight',
            field=models.IntegerField(default=-1),
        ),
    ]
