# Generated by Django 2.0.1 on 2018-04-24 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20180414_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentvote',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ideavote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideavote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
